### GET request to WorkflowController with query parameters
GET https://localhost:7209/api/workflow/22222222-2222-2222-2222-222222222222
    ?subjectDid=did:example:123
    &exampleClaim=ClaimValueXYZ
    &peerDid=did:example:456
    &email=testuser@example.com
    &testClaim=RandomStringABC

### POST request to WorkflowController with JSON body
POST https://localhost:7209/api/workflow/c8a4d381-c060-4e5d-0940-08dd448c10c5
Content-Type: application/json

{
  "subjectDid": "did:example:123",
  "exampleClaim": "ClaimValueXYZ",
  "peerDid": "did:example:456",
  "email": "testuser@example.com",
  "age": "123"
}
