### GET request to WorkflowController with query parameters
GET https://localhost:7209/api/workflow/22222222-2222-2222-2222-222222222222
    ?subjectDid=did:example:123
    &exampleClaim=ClaimValueXYZ
    &peerDid=did:example:456
    &email=testuser@example.com
    &testClaim=RandomStringABC

### POST request to WorkflowController with JSON body
POST https://localhost:7209/api/workflow/7b818f8a-5ba0-4b86-0807-08dd58266d58
Content-Type: application/json

{
  "subjectDid": "did:prism:85958de731e812d7cb30133660abc528ece48baeccc6c76a2a20c8e3c93f1ac2",
  "exampleClaim": "ClaimValueXYZ",
  "peerDid": "did:peer:2.Ez6LSq8zi2uUmB3FUyEhmQyJcM9vz5KFcVU3wVpGkgg2JnLpf.Vz6MkhLPbZsmWRbaY9oNiJB8MRbNHs5XW9ftpJDmi5PgbcPAt.SeyJpZCI6Im5ldy1pZCIsInQiOiJkbSIsInMiOnsidXJpIjoiZGlkOnBlZXI6Mi5FejZMU3BDQVVmUjg3ZHlrWHRmWXo2b2lTdWJRdGJqNVZTSjFERXBXeTFOUnlnMlptLlZ6Nk1rcWV6M3RkMUMzYzN2ZmpmTkJaSldnenZHUFhMb01OZXVVZkVZdE5aQW92MXEuU2V5SjBJam9pWkcwaUxDSnpJanA3SW5WeWFTSTZJbWgwZEhBNkx5OXRaV1JwWVhSdmNpNWliRzlqYTNSeWRYTjBMbVJsZGk4aUxDSnlJanBiWFN3aVlTSTZXeUprYVdSamIyMXRMM1l5SWwxOWZRIiwiciI6W10sImEiOlsiZGlkY29tbS92MiJdfX0",
  "email": "testuser@example.com",
  "age": "123"
}


### POST request to WorkflowController with JSON body
POST https://localhost:7209/api/workflow/3d3bd575-a76c-45fb-88e6-08dd596d541a/didcomm/presentation-request
Content-Type: application/json

{
  "senderPeerDid": "did:peer:2.Ez6LSoXb5zerVyNZXeJ7zTh1WCo4sykwaCjGzNbLXcGaBY1A3.Vz6MkgH2TQBqF1TCMvnKXWy1UwHfTK9rSuXEAaeLu86VbEZh3.SeyJpZCI6Im5ldy1pZCIsInQiOiJkbSIsInMiOnsidXJpIjoiZGlkOnBlZXI6Mi5FejZMU2tnMXd5SFVNZ01XWmlEZkJSWnBYOGFaNm5oM0VaV2ljeEpUNFZnZWdCNURiLlZ6Nk1rano4RDlxeGd1ZER2WjluVW13cGl0a1lBOVB3OXFOQW1YeEJreGNGYnRGY3MuU2V5SjBJam9pWkcwaUxDSnpJanA3SW5WeWFTSTZJbWgwZEhBNkx5OXRaV1JwWVhSdmNpNWliRzlqYTNSeWRYTjBMbVJsZGk4aUxDSnlJanBiWFN3aVlTSTZXeUprYVdSamIyMXRMM1l5SWwxOWZRIiwiciI6W10sImEiOlsiZGlkY29tbS92MiJdfX0"
}

